/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.paranavai.armarios.visao;

import br.edu.ifpr.paranavai.armarios.conexao.Conexao;
import br.edu.ifpr.paranavai.armarios.controle.LocalizacaoControle;
import br.edu.ifpr.paranavai.armarios.modelo.Localizacao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class ExemploLocalizacaoAula extends javax.swing.JFrame {

    List<Localizacao> lista = new ArrayList<>();
    /**
     * Creates new form ExemploLocalizacaoAula
     */
    public ExemploLocalizacaoAula() {
        initComponents();
//        populaTabela();
        lista = LocalizacaoControle.listarTodasLocalizacoes();
        populaCorreto(lista);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        txtFiltro = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        painelInferior = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(botaoBuscar)
                .addGap(23, 23, 23))
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSuperiorLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34))
        );

        getContentPane().add(painelSuperior, java.awt.BorderLayout.PAGE_START);

        painelInferior.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "#", "#"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        painelInferior.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelInferior, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.buscar();
    }                                           

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExemploLocalizacaoAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExemploLocalizacaoAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExemploLocalizacaoAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExemploLocalizacaoAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExemploLocalizacaoAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel painelInferior;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration                   

    private void populaTabela() {
        List<Localizacao> lista = new ArrayList<>();
        String sql = "SELECT * FROM tb_localizacao";

        DefaultTableModel modeloDeColunasDaTabela = (DefaultTableModel) jTable1.getModel();

        while (modeloDeColunasDaTabela.getRowCount() != 0) {
            modeloDeColunasDaTabela.removeRow(0);
        }

        try {
            PreparedStatement preparedStatement = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparedStatement.executeQuery();
            while (resultado.next()) {
                Object[] dadosLinha = new Object[4];
                dadosLinha[0] = resultado.getInt("id_localizacao");
                dadosLinha[1] = resultado.getString("nome");
                modeloDeColunasDaTabela.addRow(dadosLinha);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    

    private void populaCorreto(List<Localizacao> lista) {

        DefaultTableModel modeloDeColunasDaTabela = (DefaultTableModel) jTable1.getModel();

        while (modeloDeColunasDaTabela.getRowCount() != 0) {
            modeloDeColunasDaTabela.removeRow(0);
        }

        for (Localizacao localizacao : lista) {
            Object[] dadosLinha = new Object[2];
            dadosLinha[0] = localizacao.getLocalizacaoId();
            dadosLinha[1] = localizacao.getNome();
            modeloDeColunasDaTabela.addRow(dadosLinha);
        }
    }

    

    private void buscar() {
        List<Localizacao> listaAtualizada = new ArrayList<Localizacao>();
        
        for (int i = 0; i < lista.size(); i++) {
            if(lista.get(i).getNome().toUpperCase().contains(txtFiltro.getText().toUpperCase())){
                listaAtualizada.add(lista.get(i));
            }
        }
        populaCorreto(listaAtualizada);
    }

}
